version: "3.8"

services:
  # db: # EXPOSED_PORT = 5432
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - ${VOLUME_NAME-app-db-data}:/var/lib/postgresql/data/pgdata
  #   environment:
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   env_file:
  #     - .env
  #   expose:
  #     - "5432"

  api:
    build:
      context: .  
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: dotnet WebApi.dll